QUEERPETS/queer_pets/config/routes.rb
Rails.application.routes.draw do

  root 'shelters#index'

  resources :shelters do
  	
    resources :animals do 
    	get '/adopt' => 'animals#adopt'
    end
    resources :clients
  end
  
end

QUEERPETS/queer_pets/app/models/animal.rb
class Animal < ActiveRecord::Base
	belongs_to :shelter
	has_one :client
end

QUEERPETS/queer_pets/app/models/client.rb
class Client < ActiveRecord::Base
	has_many :animals
	belongs_to :shelter
end

QUEERPETS/queer_pets/app/models/shelter.rb
class Shelter < ActiveRecord::Base
	has_many :animals
	has_many :clients
end

QUEERPETS/queer_pets/app/controllers/animals_controller.rb
class AnimalsController < ApplicationController

	def index
		@shelter = Shelter.find(params[:shelter_id])
		@animals = @shelter.animals
	end

	def show
		@animal = Animal.find(params[:id])
	end

	def new
		@shelter = Shelter.find(params[:shelter_id])
		@animal = @shelter.animals.new
	end

	def create
		@shelter = Shelter.find(params[:shelter_id])
		@animal = @shelter.animals.new(animal_params)
		if @animal.save
			redirect_to shelter_path(@shelter)
		end
	end

	def adopt
		@shelter = Shelter.find(params[:shelter_id])
		@animal = @shelter.animals.find(params[:id])
	end

	def update
		@shelter = Shelter.find(params[:shelter_id])
		@animal = @shelter.animals.find(params[:id])
		if @animal.update(adoption_params)
			redirect_to shelter_path
		end
	end

	private

	def adoption_params
		params.require(:animal).permit(:client_id)
	end

end

QUEERPETS/queer_pets/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

QUEERPETS/queer_pets/app/controllers/clients_controller.rb
class ClientsController < ApplicationController

	def index
		@shelter = Shelter.find(params[:shelter_id])
		@clients = @shelter.clients.all
	end

	def show
		@shelter = Shelter.find(params[:shelter_id])
		@client = @shelter.clients.find(params[:id])
	end

	def edit
		@shelter = Shelter.find(params[:shelter_id])
		@client = @shelter.clients.find(params[:id])
	end

	def update
		@client = Client.find(params[:id])
		if @client.update(client_params)
			redirect_to shelter_client_path
		end
	end

	def new
		@shelter = Shelter.find(params[:shelter_id])
		@client = @shelter.clients.new
	end

	def create
		@shelter = Shelter.find(params[:shelter_id])
		@client = @shelter.clients.new(client_params)
		if @client.save
			redirect_to shelter_clients_path
		end
	end

	private

	def client_params
		params.require(:client).permit(:name,:age,:shelter_id)
	end
	
end

QUEERPETS/queer_pets/app/controllers/shelters_controller.rb
class SheltersController < ApplicationController

	def index
		@shelters = Shelter.all
	end

	def show
		@shelter = Shelter.find(params[:id])
		@animals = @shelter.animals
		@clients = @shelter.clients
	end

	def new
		@shelter = Shelter.new
	end

	def create
		@shelter = Shelter.new(shelter_params)
		if @shelter.save
			redirect_to root_path
		end
	end

	private

	def shelter_params
		params.require(:shelter).permit(:name)
	end

end

QUEERPETS/queer_pets/app/helpers/application_helper.rb
module ApplicationHelper
end

QUEERPETS/queer_pets/app/views/animals/_form.html.erb
<%= form_for [@shelter, @animal] do |a| %>
  <p>Client: <%= collection_select(:animal, :client_id, Client.all, :id, :name) %></p>
  <p><%= a.submit %>
<% end %>

QUEERPETS/queer_pets/app/views/animals/adopt.html.erb
<h2>adoption page</h2>
<%= @animal.name %>
<%= render 'form' %>

QUEERPETS/queer_pets/app/views/animals/edit.html.erb
<p>Edit Animal</p>
<%= render 'form' %>

QUEERPETS/queer_pets/app/views/animals/index.html.erb
<p>here be animals</p>

<% @animals.each do |a| %>
  <p><%= link_to a.name, [a.shelter, a] %></p>
<% end %>

<p><%= link_to 'new animal', new_shelter_animal_path %></p>

QUEERPETS/queer_pets/app/views/animals/new.html.erb
<p>New Animal</p>
<%= render 'form' %>

QUEERPETS/queer_pets/app/views/animals/show.html.erb
<p><%= @animal.name %></p>

<p><%= link_to 'adopt animal', shelter_animal_adopt_path(@animal) %></p>

QUEERPETS/queer_pets/app/views/clients/_form.html.erb
<%= form_for [@shelter, @client] do |c| %>
  <p>Name: <%= c.text_field :name %></p>
  <p>Age: <%= c.number_field :age %></p>
  <p>Shelter: <%= collection_select(:client, :shelter_id, Shelter.all, :id, :name) %></p>
  <p><%= c.submit %>
<% end %>

QUEERPETS/queer_pets/app/views/clients/edit.html.erb
<p>Edit Client</p>
<%= render 'form' %>

QUEERPETS/queer_pets/app/views/clients/index.html.erb
<h1>here be clients</h1>

<% @clients.each do |c| %>
<p><%= link_to c.name, client_path(c) %></p>
<% end %>

<p><%= link_to 'new client', new_client_path %></p>

QUEERPETS/queer_pets/app/views/clients/new.html.erb
<h2>New Client</h2>
<%= render 'form' %>

QUEERPETS/queer_pets/app/views/clients/show.html.erb
<h2><%= @client.name %></h2>
<p>Shelter: <%= @client.shelter.name %></p>

<%= link_to 'edit client', edit_shelter_client_path %>

QUEERPETS/queer_pets/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>QueerPets</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

QUEERPETS/queer_pets/app/views/shelters/index.html.erb
<p>here be shelters</p>

<% @shelters.each do |sh| %>
  <p><%= link_to sh.name, shelter_path(sh) %></p>
<% end %>

<p><%= link_to 'new shelter', new_shelter_path %></p>

QUEERPETS/queer_pets/app/views/shelters/new.html.erb
<%= form_for [@shelter] do |sh| %>
	<p>Name: <%= sh.text_field :name %></p>
	<p><%= sh.submit %></p>
<% end %>

QUEERPETS/queer_pets/app/views/shelters/show.html.erb
<p><%= @shelter.name %></p>

<h3>Animals</h3>
<% @animals.each do |a| %>
	<p><%= link_to a.name, [a.shelter, a] %></p>
<% end %>

<h2><%= link_to 'new animal', new_shelter_animal_path(@shelter) %></h2>

<h3>Clients</h3>
<% @clients.each do |c| %>
  <p><%= link_to c.name, [c.shelter, c] %></p>
<% end %>

<h2><%= link_to 'new client', new_shelter_client_path(@shelter) %></h2>